### ISSUE TITLE
Error in console when running "Tint: New Terminal in Tab"

### ISSUE THREAD

**Issue by aziz** [yyyc514/Tint#1]
```
Traceback (most recent call last):
  File "/opt/homebrew-cask/Caskroom/sublime-text-dev/Build 3062/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 535, in run_
    return self.run()
  File "commands.new_terminal in /Users/allen.bargi/Library/Application Support/Sublime Text 3/Installed Packages/Tint.sublime-package", line 32, in run
IndexError: list index out of range
```

**Comment by joshgoebel** [comment]
You need at least one folder open... do you not have anything open?

**Comment by joshgoebel** [comment]
On Mac the working directly is `/Applications/Sublime Text.app/Contents/MacOS` if you don't have a folder open... I'm not sure opening a terminal there makes sense.

Thoughts? 

Should we just raise an error if no folders are open?

**Comment by joshgoebel** [comment]
Actually, we could start in HOME.

**Comment by joshgoebel** [comment]
Try 0.1.4.  It tries folders, then HOME, then finally gives up to `pwd` in the last case.

**Comment by joshgoebel** [comment]
Good catch. :)

**Comment by aziz** [comment]
Now it works. Good job. :+1:
