### ISSUE TITLE
Failed on Fedora

### ISSUE THREAD

**Issue by marcioAlmada** [yyyc514/Tint#2]
Output on console:

```
data entry
('zsh', '-l', '-c', '([[ -f ~/.zshrc ]] && source ~/.zshrc); ls -la')
Traceback (most recent call last):
  File "tint in /home/marcio/.config/sublime-text-3/Installed Packages/Tint.sublime-package", line 32, in <lambda>
  File "tint in /home/marcio/.config/sublime-text-3/Installed Packages/Tint.sublime-package", line 43, in run_async
  File "util.runner in /home/marcio/.config/sublime-text-3/Installed Packages/Tint.sublime-package", line 52, in run
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'zsh'
```

What should I do? I have bash :)

**Comment by joshgoebel** [comment]
Create a config file and change the "shell" setting to "bash"?

**Comment by joshgoebel** [comment]
There should be menu options to view the default config.

**Comment by joshgoebel** [comment]
Let me know if that works.  I'll leave this open either way - I probably should change the default to be Bash.

**Comment by marcioAlmada** [comment]
Worked. Thanks!
